pub const RETRO_API_VERSION: u32 = 1;
pub const REGION_NTSC: u32 = 0;

pub const RETRO_ENVIRONMENT_SET_PIXEL_FORMAT: u32 = 10;
pub const RETRO_ENVIRONMENT_GET_VARIABLE: u32 = 15;
pub const RETRO_ENVIRONMENT_SET_VARIABLES: u32 = 16;
pub const RETRO_ENVIRONMENT_GET_VARIABLE_UPDATE: u32 = 17;
pub const RETRO_ENVIRONMENT_SET_CONTENT_INFO_OVERRIDE: u32 = 65;
pub const RETRO_ENVIRONMENT_GET_GAME_INFO_EXT: u32 = 66;

pub const RETRO_PIXEL_FORMAT_0RGB1555: usize = 0;
pub const RETRO_PIXEL_FORMAT_XRGB8888: usize = 1;
pub const RETRO_PIXEL_FORMAT_RGB565: usize = 2;

pub const RETRO_MEMORY_SAVE_RAM: u32 = 0;
pub const RETRO_MEMORY_SYSTEM_RAM: u32 = 0;

pub const RETRO_DEVICE_JOYPAD: usize = 1;

pub const RETRO_DEVICE_ID_JOYPAD_B: isize = 0;
pub const RETRO_DEVICE_ID_JOYPAD_Y: isize = 1;
pub const RETRO_DEVICE_ID_JOYPAD_SELECT: isize = 2;
pub const RETRO_DEVICE_ID_JOYPAD_START: isize = 3;
pub const RETRO_DEVICE_ID_JOYPAD_UP: isize = 4;
pub const RETRO_DEVICE_ID_JOYPAD_DOWN: isize = 5;
pub const RETRO_DEVICE_ID_JOYPAD_LEFT: isize = 6;
pub const RETRO_DEVICE_ID_JOYPAD_RIGHT: isize = 7;
pub const RETRO_DEVICE_ID_JOYPAD_A: isize = 8;
pub const RETRO_DEVICE_ID_JOYPAD_X: isize = 9;
pub const RETRO_DEVICE_ID_JOYPAD_L: isize = 10;
pub const RETRO_DEVICE_ID_JOYPAD_R: isize = 11;
pub const RETRO_DEVICE_ID_JOYPAD_L2: isize = 12;
pub const RETRO_DEVICE_ID_JOYPAD_R2: isize = 13;
pub const RETRO_DEVICE_ID_JOYPAD_L3: isize = 14;
pub const RETRO_DEVICE_ID_JOYPAD_R3: isize = 15;
